### PR TITLE
Add GNU GPL licence

### LINKED ISSUE #3: Add GNU GPL licence
Need to be done.
Also, repository contains compiled antlr4, so it's licence need to be placed to.

### PR DESCRIPTION
**Pull request by yunusbulutt**

### CODE REVIEW

**Review by daihaminkey — CHANGES_REQUESTED** [review]
It's my first attempt to publish something under licence, but as I understand, there is no need to have all this text, only part. As it stated it licence itself:
```
If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper mail.
```

**Comment by daihaminkey** [comment]
I think, the text should be:
```
atlr4-grammar-compiler
Copyright (C) 2020  Timophey Khakhanov

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

If I understand it right...

**Comment by yunusbulutt** [comment]
Is it enough just to add the specified part? If you want, I can send a pull request again.

**Comment by daihaminkey** [comment]
> 
> 
> Is it enough just to add the specified part? If you want, I can send a pull request again.

Yes, I think it's the right way. You can update file in this pull request with specified text and I'll merge it. Thank you.

**Review by daihaminkey — APPROVED** [review]
Now thing are serious, we have a licence. Thank you.

**Comment by yunusbulutt** [comment]
You're welcome. @daihaminkey  I think the other issue was a problem.

**Comment by daihaminkey** [comment]
Yep, if I understand it right, there was replay in wrong issue. It's ok, I handled it. I'll make translation to English later, I think, this project might be interesting to international community. Saved me a lot of time last summer.
@yunusbulutt

**Comment by yunusbulutt** [comment]
Hi @daihaminkey Could you please add the label "hacktoberfest-accepted" if you please? :))

**Pull request merged**
